// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4UblZslSdSsBfgKMDbjEGkiUwdkfEBvA',
    appId: '1:767827909880:web:bb98d6d65ec26e04a02f0d',
    messagingSenderId: '767827909880',
    projectId: 'thyondelivery',
    authDomain: 'thyondelivery.firebaseapp.com',
    storageBucket: 'thyondelivery.firebasestorage.app',
    measurementId: 'G-G581X8CHTZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABzBkYadmrsele2OBC6wdDDka0CFhiRX8',
    appId: '1:767827909880:ios:9bce265e55982b2da02f0d',
    messagingSenderId: '767827909880',
    projectId: 'thyondelivery',
    storageBucket: 'thyondelivery.firebasestorage.app',
    iosBundleId: 'com.example.thydeliveryMobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4UblZslSdSsBfgKMDbjEGkiUwdkfEBvA',
    appId: '1:767827909880:web:054f6f0ab896b675a02f0d',
    messagingSenderId: '767827909880',
    projectId: 'thyondelivery',
    authDomain: 'thyondelivery.firebaseapp.com',
    storageBucket: 'thyondelivery.firebasestorage.app',
    measurementId: 'G-82XLQHXJ89',
  );
}
